/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author frank
 */
public class GUI extends javax.swing.JFrame {

    private Liste sl = new Liste();

    public GUI() {
        initComponents();
        String[][] td = new String[11][4];
        td[0][0] = "Braun";
        td[0][1] = "Mark";
        td[0][2] = "01.02.2000";
        td[0][3] = String.valueOf((int) Math.round(Math.random() * 13));
        td[1][0] = "Labeck";
        td[1][1] = "Victoria";
        td[1][2] = "03.04.2001";
        td[1][3] = String.valueOf((int) Math.round(Math.random() * 13));
        td[2][0] = "Berg";
        td[2][1] = "Marvin";
        td[2][2] = "01.05.2002";
        td[2][3] = String.valueOf((int) Math.round(Math.random() * 13));
        td[3][0] = "Kaste";
        td[3][1] = "Hans";
        td[3][2] = "20.011.2003";
        td[3][3] = String.valueOf((int) Math.round(Math.random() * 13));
        td[4][0] = "Arnold";
        td[4][1] = "Elias";
        td[4][2] = "04.02.2001";
        td[4][3] = String.valueOf((int) Math.round(Math.random() * 13));
        td[5][0] = "FÃ¶mmel";
        td[5][1] = "Jonas";
        td[5][2] = "17.12.2002";
        td[5][3] = String.valueOf((int) Math.round(Math.random() * 13));
        td[6][0] = "Heldt";
        td[6][1] = "Jonas";
        td[6][2] = "01.02.2001";
        td[6][3] = String.valueOf((int) Math.round(Math.random() * 13));
        td[7][0] = "Ateyeh";
        td[7][1] = "Marta";
        td[7][2] = "23.09.2002";
        td[7][3] = String.valueOf((int) Math.round(Math.random() * 13));
        td[8][0] = "Remmel";
        td[8][1] = "Theo";
        td[8][2] = "11.05.2000";
        td[8][3] = String.valueOf((int) Math.round(Math.random() * 13));
        td[9][0] = "Topsch";
        td[9][1] = "Frank";
        td[9][2] = "21.05.1975";
        td[9][3] = "15";
        td[10][0] = "Gott";
        td[10][1] = "der liebe";
        td[10][2] = "???";
        td[10][3] = "14";
        for(int i=0;i<td.length;i++){
            Schueler neuerSchueler=new Schueler(Integer.valueOf(td[i][3]),td[i][0],td[i][1],td[i][2]);
            Knoten<Schueler> neuerKnoten = new Knoten<Schueler>(neuerSchueler);
                sl.add(neuerKnoten);
        }
ta_original.setText(sl.toString());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        b_sort = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        ta_original = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        ta_erg = new javax.swing.JTextArea();
        tausche_a = new javax.swing.JTextField();
        tausche_b = new javax.swing.JTextField();
        b_tausche = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        l_anz = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        b_sort.setText("Sortieren");
        b_sort.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                b_sortMouseClicked(evt);
            }
        });

        ta_original.setColumns(20);
        ta_original.setRows(5);
        jScrollPane1.setViewportView(ta_original);

        ta_erg.setColumns(20);
        ta_erg.setRows(5);
        jScrollPane2.setViewportView(ta_erg);

        tausche_a.setText("3");

        tausche_b.setText("7");

        b_tausche.setText("Tauschen");
        b_tausche.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                b_tauscheMouseClicked(evt);
            }
        });

        jLabel1.setText("Anzahl Knoten:");

        l_anz.setText("0");

        jLabel2.setText("Knoten a:");

        jLabel3.setText("Knoten b:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 263, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 61, Short.MAX_VALUE)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 263, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32))
            .addGroup(layout.createSequentialGroup()
                .addGap(88, 88, 88)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(tausche_a, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(tausche_b, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(62, 62, 62)
                                .addComponent(b_tausche))
                            .addComponent(b_sort)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addComponent(l_anz, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 458, Short.MAX_VALUE)
                    .addComponent(jScrollPane1))
                .addGap(18, 18, 18)
                .addComponent(b_sort)
                .addGap(11, 11, 11)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(l_anz))
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tausche_a, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tausche_b, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(b_tausche)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3))
                .addGap(37, 37, 37))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void b_sortMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_b_sortMouseClicked
        sl.quicksort(sl);
        ta_erg.setText(sl.toStringrekursiv());
        l_anz.setText(String.valueOf(sl.getAnzahl()));
    }//GEN-LAST:event_b_sortMouseClicked

    private void b_tauscheMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_b_tauscheMouseClicked
        int anz=sl.getAnzahl();
        int n_a = Integer.parseInt(tausche_a.getText());
        int n_b = Integer.parseInt(tausche_b.getText());
        if (n_a <anz && n_b <anz){
            Knoten a = sl.getKnoten(n_a);
            Knoten b = sl.getKnoten(n_b);
            sl.tausche(a,b);
            ta_erg.setText(sl.toStringrekursiv());
        }else{
            System.out.println("a oder b grÃ¶ÃŸer als Anzahl der Knoten");
        }
    }//GEN-LAST:event_b_tauscheMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton b_sort;
    private javax.swing.JButton b_tausche;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel l_anz;
    private javax.swing.JTextArea ta_erg;
    private javax.swing.JTextArea ta_original;
    private javax.swing.JTextField tausche_a;
    private javax.swing.JTextField tausche_b;
    // End of variables declaration//GEN-END:variables
}
